# Generated by Django 4.2.3 on 2023-08-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
