# Generated by Django 4.2.3 on 2023-08-10 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='slug')),
                ('content', models.CharField(max_length=250, verbose_name='Cодержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='превью ')),
                ('date_creation', models.TimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('is_publication', models.BooleanField(verbose_name='Опубликовано')),
                ('number_of_views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('header',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.TimeField(blank=True, null=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('purchase_price', models.IntegerField(verbose_name='Цена за покупку')),
                ('date_of_creation', models.TimeField(blank=True, null=True, verbose_name='дата создания')),
                ('last_modified_date', models.TimeField(blank=True, null=True, verbose_name='дата последнего изменения')),
                ('number_of_views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='Номер версии')),
                ('version_name', models.CharField(max_length=100, verbose_name='Название версии')),
                ('is_active_version', models.BooleanField(verbose_name='Признак версии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='main.product')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
                'ordering': ('version_number',),
            },
        ),
    ]
