# Generated by Django 4.2.3 on 2023-07-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.TimeField(blank=True, null=True, verbose_name='дата создания'),
        ),
    ]
