# Generated by Django 4.2.3 on 2023-07-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_date_of_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('content', models.CharField(max_length=250, verbose_name='Cодержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='превью ')),
                ('date_creation', models.TimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('is_publication', models.BooleanField(verbose_name='Опубликовано')),
                ('number_of_views', models.IntegerField(verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ('header',),
            },
        ),
    ]
