# Generated by Django 4.2.3 on 2023-07-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_blog_options_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='превью '),
        ),
    ]
