# Generated by Django 4.2.3 on 2023-08-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('version_number',), 'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
    ]
